'use client'

import { useState, useTransition } from 'react'
import { adminPublishPlanVersionAction, adminRevokeVenueOverrideAction, adminSetAccountPlanAction, adminSetVenueOverrideAction, adminUpdateAddonAction, adminUpdateBillingSettingAction, adminUpdateDeliveryStatusAction, adminUpdatePlanShellAction } from '@/actions/billing/admin'

type Version = { version: number; monthlyPrice: number; annualPrice: number; maxLocations: number | null; maxMembers: number | null; maxMediaPerVenue: number | null; googlePhotoEnabled: boolean; menuEnabled: boolean; servicesEnabled: boolean; monthlyEventsPerVenue: number | null; maxActivePromotionsPerVenue: number | null; analyticsRetentionDays: number | null; whatsappEnabled: boolean; messagingEnabled: boolean; reservationsEnabled: boolean; priorityModeration: boolean; includedBoostCredits: number }
type Plan = { slug: string; name: string; description: string | null; displayOrder: number; isPublished: boolean; isArchived: boolean; latest: Version | null }
type Addon = { slug: string; name: string; description: string | null; price: number; durationDays: number | null; requiresDelivery: boolean; displayOrder: number; isPublished: boolean; isArchived: boolean }
type Account = { id: string; owner: { name: string | null; email: string }; activePlan: string; venues: number; members: number }
type Venue = { id: string; name: string; accountId: string | null; inheritedPlan: string; overridePlan: string | null }
type Totals = { requests: number; successes: number; errors: number; quotaErrors: number }
type Props = { plans: Plan[]; addons: Addon[]; accounts: Account[]; venues: Venue[]; simulationEnabled: boolean; googlePhotoEnabled: boolean; google: { current: Totals; previous: Totals; topVenues: Array<{ name: string; requests: number; successes: number; errors: number }> }; orders: Array<{ id: string; kind: string; status: string; product: string; referenceAmount: number; chargedAmount: number; currency: string; createdAt: string; buyer: { email: string } }>; deliveries: Array<{ id: string; deliveryStatus: string; createdAt: string; addonProduct: { name: string }; buyer: { email: string }; venue: string | null }>; audit: Array<{ id: string; action: string; reason: string | null; createdAt: string; actor: { email: string }; account: string | null; venue: string | null }> }

const input = 'min-h-10 rounded-lg border border-border bg-background px-3 text-sm'
const button = 'min-h-10 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50'
const card = 'rounded-2xl border border-border/60 bg-card p-5'
const numberOrNull = (value: FormDataEntryValue | null) => value === '' || value === null ? null : Number(value)

export function AdminBillingPanel(props: Props) {
  const [pending, startTransition] = useTransition()
  const [message, setMessage] = useState<string | null>(null)
  const [selectedAccount, setSelectedAccount] = useState(props.accounts[0]?.id ?? '')
  const [selectedVenue, setSelectedVenue] = useState(props.venues[0]?.id ?? '')
  const [accountPlan, setAccountPlan] = useState('plus')
  const [venuePlan, setVenuePlan] = useState('pro')
  const [cycle, setCycle] = useState<'MONTHLY' | 'ANNUAL'>('MONTHLY')
  const run = (action: () => Promise<{ success: boolean; error?: string }>, success: string) => startTransition(async () => { const result = await action(); setMessage(result.success ? success : result.error ?? 'No se pudo guardar.') })

  return <div className="space-y-8">
    {message && <p role="status" className="sticky top-3 z-20 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{message}</p>}
    <section className={card}><h2 className="text-xl">Controles beta</h2><p className="mt-1 text-sm text-muted-foreground">La simulación no solicita tarjeta ni genera cobros reales.</p><div className="mt-4 flex flex-wrap gap-6 text-sm"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" defaultChecked={props.simulationEnabled} onChange={(e) => run(() => adminUpdateBillingSettingAction({ simulationEnabled: e.target.checked }), 'Simulación actualizada.')} /> Activación beta</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" defaultChecked={props.googlePhotoEnabled} onChange={(e) => run(() => adminUpdateBillingSettingAction({ googlePhotoEnabled: e.target.checked }), 'Google Places actualizado.')} /> Fotos de Google</label></div></section>

    <section className="space-y-4"><div><h2 className="text-2xl">Catálogo y versiones</h2><p className="text-sm text-muted-foreground">El shell controla visibilidad. Publicar crea una versión inmutable.</p></div>{props.plans.map((plan) => <PlanEditor key={plan.slug} plan={plan} pending={pending} run={run} />)}</section>

    <section className="space-y-4"><div><h2 className="text-2xl">Extras</h2><p className="text-sm text-muted-foreground">Precio, vigencia, entrega y publicación.</p></div><div className="grid gap-4 lg:grid-cols-2">{props.addons.map((addon) => <AddonEditor key={addon.slug} addon={addon} pending={pending} run={run} />)}</div></section>

    <section className={`${card} space-y-4`}><h2 className="text-xl">Planes por cuenta y local</h2><div className="grid gap-3 lg:grid-cols-[2fr_1fr_1fr_auto]"><select className={input} value={selectedAccount} onChange={(e) => setSelectedAccount(e.target.value)}>{props.accounts.map((a) => <option key={a.id} value={a.id}>{a.owner.name ?? a.owner.email} · {a.activePlan} · {a.venues} locales</option>)}</select><select className={input} value={accountPlan} onChange={(e) => setAccountPlan(e.target.value)}>{props.plans.map((p) => <option key={p.slug} value={p.slug}>{p.name}</option>)}</select><select className={input} value={cycle} onChange={(e) => setCycle(e.target.value as 'MONTHLY' | 'ANNUAL')}><option value="MONTHLY">Mensual</option><option value="ANNUAL">Anual</option></select><button className={button} disabled={pending || !selectedAccount} onClick={() => run(() => adminSetAccountPlanAction({ accountId: selectedAccount, planSlug: accountPlan, cycle, reason: 'Ajuste desde consola de monetización' }), 'Plan de cuenta actualizado.')}>Asignar</button></div><div className="grid gap-3 lg:grid-cols-[2fr_1fr_auto_auto]"><select className={input} value={selectedVenue} onChange={(e) => setSelectedVenue(e.target.value)}>{props.venues.map((v) => <option key={v.id} value={v.id}>{v.name} · {v.overridePlan ? `override ${v.overridePlan}` : `hereda ${v.inheritedPlan}`}</option>)}</select><select className={input} value={venuePlan} onChange={(e) => setVenuePlan(e.target.value)}>{props.plans.map((p) => <option key={p.slug} value={p.slug}>{p.name}</option>)}</select><button className={button} disabled={pending || !selectedVenue} onClick={() => run(() => adminSetVenueOverrideAction({ venueId: selectedVenue, planSlug: venuePlan, reason: 'Override desde consola de monetización' }), 'Override aplicado.')}>Aplicar</button><button className={`${input} font-semibold`} disabled={pending || !selectedVenue} onClick={() => run(() => adminRevokeVenueOverrideAction(selectedVenue, 'Restauración desde consola de monetización'), 'Herencia restaurada.')}>Revocar</button></div></section>

    <GooglePanel {...props.google} />
    <section className={card}><h2 className="text-xl">Entregas pendientes</h2><div className="mt-4 space-y-3">{props.deliveries.length === 0 ? <p className="text-sm text-muted-foreground">No hay entregas pendientes.</p> : props.deliveries.map((d) => <div key={d.id} className="flex flex-wrap items-center justify-between gap-3 border-b pb-3 text-sm"><span><b>{d.addonProduct.name}</b> · {d.buyer.email} · {d.venue ?? 'Sin local'}</span><select className={input} value={d.deliveryStatus} onChange={(e) => run(() => adminUpdateDeliveryStatusAction(d.id, e.target.value as 'PENDING' | 'IN_PROGRESS' | 'DELIVERED'), 'Entrega actualizada.')}><option value="PENDING">Pendiente</option><option value="IN_PROGRESS">En proceso</option><option value="DELIVERED">Entregado</option></select></div>)}</div></section>
    <DataTable title="Órdenes recientes" rows={props.orders.map((o) => [o.product, o.buyer.email, o.status, `${o.currency} ${o.referenceAmount.toFixed(2)} / cobrado ${o.chargedAmount.toFixed(2)}`, new Date(o.createdAt).toLocaleString('es-EC')])} />
    <DataTable title="Auditoría" rows={props.audit.map((a) => [a.action, a.actor.email, a.account ?? a.venue ?? 'Global', a.reason ?? '—', new Date(a.createdAt).toLocaleString('es-EC')])} />
  </div>
}

function PlanEditor({ plan, pending, run }: { plan: Plan; pending: boolean; run: (a: () => Promise<{ success: boolean; error?: string }>, s: string) => void }) {
  const v = plan.latest
  const submitShell = (form: HTMLFormElement) => { const f = new FormData(form); run(() => adminUpdatePlanShellAction({ planSlug: plan.slug, name: f.get('name'), description: f.get('description') || null, displayOrder: Number(f.get('displayOrder')), isPublished: f.get('isPublished') === 'on', isArchived: f.get('isArchived') === 'on', reason: 'Edición del catálogo desde consola' }), 'Catálogo actualizado.') }
  const submitVersion = (form: HTMLFormElement) => { const f = new FormData(form); run(() => adminPublishPlanVersionAction({ planSlug: plan.slug, monthlyPrice: Number(f.get('monthlyPrice')), annualPrice: Number(f.get('annualPrice')), maxLocations: numberOrNull(f.get('maxLocations')), maxMembers: numberOrNull(f.get('maxMembers')), maxMediaPerVenue: numberOrNull(f.get('maxMediaPerVenue')), googlePhotoEnabled: f.get('googlePhotoEnabled') === 'on', menuEnabled: f.get('menuEnabled') === 'on', servicesEnabled: f.get('servicesEnabled') === 'on', monthlyEventsPerVenue: numberOrNull(f.get('monthlyEventsPerVenue')), maxActivePromotionsPerVenue: numberOrNull(f.get('maxActivePromotionsPerVenue')), analyticsRetentionDays: numberOrNull(f.get('analyticsRetentionDays')), whatsappEnabled: f.get('whatsappEnabled') === 'on', messagingEnabled: f.get('messagingEnabled') === 'on', reservationsEnabled: f.get('reservationsEnabled') === 'on', priorityModeration: f.get('priorityModeration') === 'on', includedBoostCredits: Number(f.get('includedBoostCredits')), reason: 'Nueva versión publicada desde consola' }), 'Nueva versión publicada.') }
  return <details className={card} open={plan.slug === 'free'}><summary className="cursor-pointer font-semibold">{plan.name} · {plan.slug} · v{v?.version ?? '—'}</summary><form className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={(e) => { e.preventDefault(); submitShell(e.currentTarget) }}><input name="name" defaultValue={plan.name} className={input} aria-label="Nombre"/><input name="description" defaultValue={plan.description ?? ''} className={`${input} lg:col-span-2`} aria-label="Descripción"/><input name="displayOrder" type="number" defaultValue={plan.displayOrder} className={input} aria-label="Orden"/><label><input name="isPublished" type="checkbox" defaultChecked={plan.isPublished}/> Publicado</label><label><input name="isArchived" type="checkbox" defaultChecked={plan.isArchived}/> Archivado</label><button className={button} disabled={pending}>Guardar catálogo</button></form>{v && <form className="mt-6 border-t pt-5" onSubmit={(e) => { e.preventDefault(); submitVersion(e.currentTarget) }}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(['monthlyPrice','annualPrice','maxLocations','maxMembers','maxMediaPerVenue','monthlyEventsPerVenue','maxActivePromotionsPerVenue','analyticsRetentionDays','includedBoostCredits'] as const).map((key) => <label key={key} className="text-xs text-muted-foreground">{key}<input name={key} type="number" step={key.includes('Price') ? '0.01' : '1'} defaultValue={v[key] ?? ''} className={`${input} mt-1 w-full text-foreground`}/></label>)}</div><div className="mt-4 flex flex-wrap gap-4 text-sm">{(['googlePhotoEnabled','menuEnabled','servicesEnabled','whatsappEnabled','messagingEnabled','reservationsEnabled','priorityModeration'] as const).map((key) => <label key={key}><input name={key} type="checkbox" defaultChecked={v[key]}/> {key}</label>)}</div><button className={`${button} mt-5`} disabled={pending}>Publicar versión {v.version + 1}</button></form>}</details>
}

function AddonEditor({ addon, pending, run }: { addon: Addon; pending: boolean; run: (a: () => Promise<{ success: boolean; error?: string }>, s: string) => void }) { return <form className={`${card} grid gap-3 sm:grid-cols-2`} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => adminUpdateAddonAction({ slug: addon.slug, name: f.get('name'), description: f.get('description') || null, price: Number(f.get('price')), durationDays: numberOrNull(f.get('durationDays')), requiresDelivery: f.get('requiresDelivery') === 'on', displayOrder: Number(f.get('displayOrder')), isPublished: f.get('isPublished') === 'on', isArchived: f.get('isArchived') === 'on', reason: 'Edición de extra desde consola' }), 'Extra actualizado.') }}><p className="sm:col-span-2 text-xs text-muted-foreground">{addon.slug}</p><input name="name" defaultValue={addon.name} className={input}/><input name="description" defaultValue={addon.description ?? ''} className={input}/><input name="price" type="number" step="0.01" defaultValue={addon.price} className={input}/><input name="durationDays" type="number" defaultValue={addon.durationDays ?? ''} placeholder="Días" className={input}/><input name="displayOrder" type="number" defaultValue={addon.displayOrder} className={input}/><div className="flex flex-wrap gap-3 text-sm"><label><input name="requiresDelivery" type="checkbox" defaultChecked={addon.requiresDelivery}/> Entrega</label><label><input name="isPublished" type="checkbox" defaultChecked={addon.isPublished}/> Publicado</label><label><input name="isArchived" type="checkbox" defaultChecked={addon.isArchived}/> Archivado</label></div><button className={button} disabled={pending}>Guardar extra</button></form> }

function GooglePanel({ current, previous, topVenues }: Props['google']) { const delta = previous.requests ? Math.round(((current.requests - previous.requests) / previous.requests) * 100) : null; return <section className={card}><h2 className="text-xl">Google Places</h2><p className="text-sm text-muted-foreground">Mes actual frente al anterior {delta === null ? '· sin base previa' : `· ${delta >= 0 ? '+' : ''}${delta}% solicitudes`}.</p><div className="mt-4 grid gap-3 sm:grid-cols-4">{(['requests','successes','errors','quotaErrors'] as const).map((k) => <p key={k}><span className="block text-2xl font-semibold">{current[k]}</span><span className="text-xs text-muted-foreground">{k} · antes {previous[k]}</span></p>)}</div><div className="mt-5 space-y-2">{topVenues.map((v) => <p key={v.name} className="flex justify-between text-sm"><span>{v.name}</span><span>{v.requests} solicitudes · {v.errors} errores</span></p>)}</div></section> }
function DataTable({ title, rows }: { title: string; rows: string[][] }) { return <section className={`${card} overflow-x-auto`}><h2 className="text-xl">{title}</h2><table className="mt-4 w-full min-w-[760px] text-left text-sm"><tbody>{rows.map((row, i) => <tr key={i} className="border-t">{row.map((cell, j) => <td key={j} className="px-2 py-3">{cell}</td>)}</tr>)}</tbody></table></section> }
