import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// IDs de las categorías creadas
const categoryIds = {
  supermercados: 'cmlywtcez0000ru705rs8b69b',
  salud: 'cmlywtcnh0001ru70n1qf0uwl',
  finanzas: 'cmlywtct60002ru700zopo7jy',
  entretenimiento: 'cmlywtcyv0003ru70lj09h4a9',
  industria: 'cmlywtd4l0004ru705hyuftda',
  educacion: 'cmlywtdab0005ru70dttvzlzu',
  cultura: 'cmlt9wbbb0007cdlo7zxchmmv', // Usar Restaurantes como categoría temporal,
  restaurantes: 'cmlt9wbbb0007cdlo7zxchmmv', // Restaurantes existente,
  compras: 'cmlywtdiv0006ru70bsexzp9e',
  servicios: 'cmlywtdoj0007ru70s2cw5gx2',
  transporte: 'cmlywtdu80008ru70o3bxvzx5',
  gobierno: 'cmlywtdzx0009ru70lwyh2abn',
  deportes: 'cmlywte5n000aru70jqolg6hi',
  vehiculos: 'cmlywtebb000bru70alq0x0sd',
  construccion: 'cmlywteh0000cru70oxryd6sx',
  telecom: 'cmlywtemq000dru7031ey5p27',
  retail: 'cmlywtesg000eru70z5scc800',
  medios: 'cmlywtey4000fru70jy8rgh3l',
  mercados: 'cmlywtf43000gru70kefiuvo7',
  ong: 'cmlywtf9s000hru70q1ywq3v3',
  alimentos: 'cmlywtffg000iru70znqov0xg',
  turismo: 'cmlywtfl5000jru70afre7pns',
  recreacion: 'cmlywtfqu000kru708c4h8q8m',
  hoteles: 'cmlt9wcfa000acdlokrf7yq7b' // Hoteles existente
}

const businesses = [
  {
    name: 'Supermaxi Loja',
    slug: 'supermaxi-loja',
    description: 'Supermercado de gran superficie',
    content: 'Supermercado con amplia variedad de productos alimenticios, hogar y tecnología. Conta con estacionamiento y horarios extendidos.',
    phone: '07-258-9123',
    email: null,
    website: 'https://www.supermaxi.com/',
    location: 'Av. Orillas del Zamora',
    lat: -3.9855,
    lng: -79.2012,
    address: 'Av. Orillas del Zamora, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.supermercados,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/supermaxi.com'
  },
  {
    name: 'Clínica San Agustín',
    slug: 'clinica-san-agustin',
    description: 'Clínica privada de salud',
    content: 'Clínica médica con servicios de consulta, laboratorio, imagenología y hospitalización. Especialistas en diversas áreas médicas.',
    phone: '07-257-0314',
    email: null,
    website: 'https://clinicasanagustin.com.ec/',
    location: '18 de Noviembre y Azuay',
    lat: -4.0013,
    lng: -79.2045,
    address: '18 de Noviembre y Azuay, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/clinicasanagustin.com.ec'
  },
  {
    name: 'Banco de Loja',
    slug: 'banco-de-loja',
    description: 'Institución bancaria local',
    content: 'Banco con servicios financieros personales y empresariales. Créditos, inversiones y servicios bancarios completos.',
    phone: '07-257-1682',
    email: null,
    website: 'https://www.bancodeloja.fin.ec/',
    location: 'Bolívar y Rocafuerte',
    lat: -3.9975,
    lng: -79.2025,
    address: 'Bolívar y Rocafuerte, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/bancodeloja.fin.ec'
  },
  {
    name: 'Farmacias Cuxibamba',
    slug: 'farmacias-cuxibamba',
    description: 'Cadena de farmacias locales',
    content: 'Farmacia con medicamentos, productos de cuidado personal y salud. Conta con servicio de delivery y atención 24/7.',
    phone: '07-257-1111',
    email: null,
    website: 'https://www.farmaciascuxibamba.com/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9965,
    lng: -79.2042,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/farmaciascuxibamba.com'
  },
  {
    name: 'Supercines Loja',
    slug: 'supercines-loja',
    description: 'Complejo de cines moderno',
    content: 'Cine con múltiples salas, tecnología digital y 3D. Barra de conchos y servicio de snacks premium.',
    phone: '07-258-8888',
    email: null,
    website: 'https://www.supercines.com/',
    location: 'Av. Orillas del Zamora (Multiplaza)',
    lat: -3.9855,
    lng: -79.2010,
    address: 'Av. Orillas del Zamora, Multiplaza, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.entretenimiento,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/supercines.com'
  },
  {
    name: 'Hospital UTPL',
    slug: 'hospital-utpl',
    description: 'Hospital universitario',
    content: 'Hospital docente de la Universidad Técnica Particular de Loja. Servicios médicos especializados y emergencias 24/7.',
    phone: '07-258-5700',
    email: null,
    website: 'https://hospitalutpl.med.ec/',
    location: 'París y San Pablo',
    lat: -3.9822,
    lng: -79.1995,
    address: 'París y San Pablo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/hospitalutpl.med.ec'
  },
  {
    name: 'ILE (Industria Lojana de Especerías)',
    slug: 'ile-industria-lojana',
    description: 'Industria alimentaria local',
    content: 'Empresa dedicada a la producción y comercialización de especias, condimentos y productos alimentarios procesados.',
    phone: '07-258-4444',
    email: null,
    website: 'https://ile.com.ec/',
    location: 'Parque Industrial',
    lat: -3.9712,
    lng: -79.2155,
    address: 'Parque Industrial, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.industria,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/ile.com.ec'
  },
  {
    name: 'Universidad Técnica Particular de Loja',
    slug: 'universidad-tecnica-particular-loja',
    description: 'Universidad privada líder',
    content: 'Universidad católica con programas de pregrado, posgrado y educación continua. Campus moderno con tecnología avanzada.',
    phone: '07-370-1444',
    email: null,
    website: 'https://www.utpl.edu.ec/',
    location: 'San Cayetano Alto',
    lat: -3.9865,
    lng: -79.1992,
    address: 'San Cayetano Alto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/utpl.edu.ec'
  },
  {
    name: 'Universidad Nacional de Loja (UNL)',
    slug: 'universidad-nacional-loja',
    description: 'Universidad pública estatal',
    content: 'Universidad pública con amplia oferta académica e investigación. Comprometida con el desarrollo regional y nacional.',
    phone: '07-254-6384',
    email: null,
    website: 'https://unl.edu.ec/',
    location: 'Ciudadela Universitaria, La Argelia',
    lat: -4.0325,
    lng: -79.2015,
    address: 'Ciudadela Universitaria, La Argelia, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/unl.edu.ec'
  },
  {
    name: 'Teatro Nacional Benjamín Carrión',
    slug: 'teatro-nacional-benjamin-carrion',
    description: 'Teatro principal de la ciudad',
    content: 'Teatro con programación cultural variada: teatro, música, danza y cine. Auditorio con excelente acústica.',
    phone: '07-258-3333',
    email: null,
    website: 'https://teatrobenjamincarrionmora.com/',
    location: 'Av. Salvador Bustamante Celi',
    lat: -3.9785,
    lng: -79.2022,
    address: 'Av. Salvador Bustamante Celi, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cultura,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/teatrobenjamincarrionmora.com'
  },
  {
    name: 'Micromercado Zerimar',
    slug: 'micromercado-zerimar',
    description: 'Mercado local de productos frescos',
    content: 'Micromercado con productos frescos, abarrotes y artículos de primera necesidad. Atención personalizada y precios competitivos.',
    phone: '07-257-4589',
    email: null,
    website: 'https://www.facebook.com/zerimarloja/',
    location: 'Av. Universitaria y Mercadillo',
    lat: -3.9982,
    lng: -79.2038,
    address: 'Av. Universitaria y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.compras,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Zerimar&background=0D8ABC&color=fff'
  },
  {
    name: 'Lojagas',
    slug: 'lojagas',
    description: 'Distribuidora de gas',
    content: 'Empresa distribuidora de gas doméstico y comercial. Servicio de entrega a domicilio y recargas de cilindros.',
    phone: '07-258-1111',
    email: null,
    website: 'https://lojagas.com.ec/',
    location: 'Av. de los Paltas',
    lat: -4.0155,
    lng: -79.2155,
    address: 'Av. de los Paltas, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.servicios,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/lojagas.com.ec'
  },
  {
    name: 'EERSSA (Empresa Eléctrica)',
    slug: 'eerssa-empresa-electrica',
    description: 'Empresa eléctrica regional',
    content: 'Empresa distribuidora de energía eléctrica. Servicios de conexión, facturación y atención al cliente.',
    phone: '07-370-0200',
    email: null,
    website: 'https://www.eerssa.gob.ec/',
    location: 'Rocafuerte y Olmedo',
    lat: -3.9995,
    lng: -79.2025,
    address: 'Rocafuerte y Olmedo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.servicios,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/eerssa.gob.ec'
  },
  {
    name: 'Hipervalle',
    slug: 'hipervalle',
    description: 'Supermercado local',
    content: 'Supermercado con productos de la canasta básica, lácteos, carnes y artículos de limpieza. Promociones semanales.',
    phone: '07-257-5555',
    email: null,
    website: 'https://www.facebook.com/Hipervalle/',
    location: 'Av. Universitaria',
    lat: -3.9925,
    lng: -79.2035,
    address: 'Av. Universitaria, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.supermercados,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Hipervalle&background=E53935&color=fff'
  },
  {
    name: 'Centro Comercial Don Daniel',
    slug: 'centro-comercial-don-daniel',
    description: 'Centro comercial local',
    content: 'Centro comercial con tiendas por departamento, comida rápida y entretenimiento. Estacionamiento gratuito.',
    phone: '07-257-7890',
    email: null,
    website: 'https://www.facebook.com/dondanielmall/',
    location: '18 de Noviembre y Chile',
    lat: -3.9902,
    lng: -79.2051,
    address: '18 de Noviembre y Chile, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.compras,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Don+Daniel+Mall&background=1E88E5&color=fff'
  },
  {
    name: 'SOLCA Núcleo de Loja',
    slug: 'solca-nucleo-loja',
    description: 'Centro de lucha contra el cáncer',
    content: 'Instituto especializado en prevención, diagnóstico y tratamiento del cáncer. Consulta externa y hospitalización.',
    phone: '07-258-5441',
    email: null,
    website: 'https://solcaloja.med.ec/',
    location: 'Av. Bernardo Valdivieso',
    lat: -4.0055,
    lng: -79.2015,
    address: 'Av. Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/solcaloja.med.ec'
  },
  {
    name: 'Hospital General Isidro Ayora',
    slug: 'hospital-general-isidro-ayora',
    description: 'Hospital público principal',
    content: 'Hospital público con servicios de emergencia, cirugía, ginecología y pediatría. Atención 24/7.',
    phone: '07-257-0540',
    email: null,
    website: 'https://www.salud.gob.ec/',
    location: 'Av. Iberoamérica',
    lat: -4.0085,
    lng: -79.2052,
    address: 'Av. Iberoamérica, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/salud.gob.ec'
  },
  {
    name: 'Terminal Terrestre Reina del Cisne',
    slug: 'terminal-terrestre-reina-cisne',
    description: 'Terminal de buses principal',
    content: 'Terminal terrestre con rutas interprovinciales e internacionales. Servicios de encomiendas y cafetería.',
    phone: '07-257-0022',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Av. 8 de Diciembre',
    lat: -3.9815,
    lng: -79.2045,
    address: 'Av. 8 de Diciembre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.transporte,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Municipio de Loja',
    slug: 'municipio-de-loja',
    description: 'Gobierno municipal',
    content: 'Gobierno local de la ciudad de Loja. Servicios administrativos, permisos y atención ciudadana.',
    phone: '07-257-0407',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Bolívar y J. Antonio Eguiguren',
    lat: -3.9971,
    lng: -79.2039,
    address: 'Bolívar y J. Antonio Eguiguren, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.gobierno,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Gobernación de Loja',
    slug: 'gobernacion-de-loja',
    description: 'Gobierno provincial',
    content: 'Gobierno provincial de Loja. Coordinación de políticas públicas y servicios a nivel provincial.',
    phone: '07-257-0234',
    email: null,
    website: 'https://www.gobernacionloja.gob.ec/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9968,
    lng: -79.2045,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.gobierno,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/gobernacionloja.gob.ec'
  },
  {
    name: 'Smart Fit Loja',
    slug: 'smart-fit-loja',
    description: 'Gimnasio moderno',
    content: 'Gimnasio con equipamiento moderno, clases grupales y entrenadores personales. Horarios flexibles.',
    phone: '099-123-4567',
    email: null,
    website: 'https://www.smartfit.com.ec/',
    location: 'Av. Orillas del Zamora (Don Daniel)',
    lat: -3.9905,
    lng: -79.2052,
    address: 'Av. Orillas del Zamora, Don Daniel, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.deportes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/smartfit.com.ec'
  },
  {
    name: 'Importadora Tomebamba',
    slug: 'importadora-tomebamba',
    description: 'Concesionario de vehículos',
    content: 'Concesionario de vehículos nuevos y usados. Servicio de mecánica, repuestos y financiamiento.',
    phone: '07-257-3333',
    email: null,
    website: 'https://www.importadoratomebamba.com.ec/',
    location: 'Av. Universitaria y Catacocha',
    lat: -4.0025,
    lng: -79.2045,
    address: 'Av. Universitaria y Catacocha, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.vehiculos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/importadoratomebamba.com.ec'
  },
  {
    name: 'Pintulac Loja',
    slug: 'pintulac-loja',
    description: 'Tienda de pinturas y construcción',
    content: 'Tienda especializada en pinturas, herramientas y materiales de construcción. Asesoría técnica.',
    phone: '07-258-2222',
    email: null,
    website: 'https://www.pintulac.com.ec/',
    location: 'Av. Universitaria',
    lat: -3.9955,
    lng: -79.2035,
    address: 'Av. Universitaria, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.construccion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/pintulac.com.ec'
  },
  {
    name: 'Kywi Loja',
    slug: 'kywi-loja',
    description: 'Ferretería grande',
    content: 'Ferretería con amplia variedad de herramientas, materiales eléctricos y plomería. Servicio de delivery.',
    phone: '07-258-1111',
    email: null,
    website: 'https://www.kywi.com.ec/',
    location: 'Av. Orillas del Zamora',
    lat: -3.9858,
    lng: -79.2015,
    address: 'Av. Orillas del Zamora, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.construccion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/kywi.com.ec'
  },
  {
    name: 'Cooperativa Padre Julián Lorente',
    slug: 'cooperativa-padre-julian-lorente',
    description: 'Cooperativa de crédito',
    content: 'Cooperativa financiera con servicios de ahorro, crédito y inversión. Atención personalizada.',
    phone: '07-257-4444',
    email: null,
    website: 'https://www.cooplorente.fin.ec/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9965,
    lng: -79.2045,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/cooplorente.fin.ec'
  },
  {
    name: 'CNT Loja',
    slug: 'cnt-loja',
    description: 'Telecomunicaciones estatales',
    content: 'Empresa de telecomunicaciones con servicios de telefonía fija, internet y televisión por cable.',
    phone: '07-257-0000',
    email: null,
    website: 'https://www.cnt.com.ec/',
    location: 'Sucre y 10 de Agosto',
    lat: -3.9958,
    lng: -79.2035,
    address: 'Sucre y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.telecom,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/cnt.com.ec'
  },
  {
    name: 'Netlife Loja',
    slug: 'netlife-loja',
    description: 'Internet de alta velocidad',
    content: 'Proveedor de internet fibra óptica con planes de alta velocidad para hogar y empresas.',
    phone: '099-999-9999',
    email: null,
    website: 'https://www.netlife.ec/',
    location: 'Av. Universitaria y Lourdes',
    lat: -4.0005,
    lng: -79.2035,
    address: 'Av. Universitaria y Lourdes, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.telecom,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/netlife.ec'
  },
  {
    name: 'Almacenes Tía Loja',
    slug: 'almacenes-tia-loja',
    description: 'Tienda por departamento',
    content: 'Tienda por departamento con ropa, hogar, electrónica y alimentos. Promociones y liquidaciones.',
    phone: '07-257-9999',
    email: null,
    website: 'https://www.tia.com.ec/',
    location: '18 de Noviembre y 10 de Agosto',
    lat: -3.9975,
    lng: -79.2048,
    address: '18 de Noviembre y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.retail,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/tia.com.ec'
  },
  {
    name: 'Radio Matovelle Loja',
    slug: 'radio-matovelle-loja',
    description: 'Radio local',
    content: 'Estación de radio con programación informativa, musical y cultural. Cobertura provincial.',
    phone: '07-257-5555',
    email: null,
    website: 'https://www.radiomatovelle.com/',
    location: 'Calle Lourdes y Sucre',
    lat: -4.0015,
    lng: -79.2055,
    address: 'Calle Lourdes y Sucre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.medios,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/radiomatovelle.com'
  },
  {
    name: 'Sonesta Hotel Loja',
    slug: 'sonesta-hotel-loja',
    description: 'Hotel de lujo',
    content: 'Hotel 5 estrellas con habitaciones elegantes, restaurante, piscina y centro de negocios. Servicio premium.',
    phone: '07-258-9000',
    email: null,
    website: 'https://www.sonestaloja.com/',
    location: 'Av. Zoilo Rodríguez',
    lat: -3.9935,
    lng: -79.1975,
    address: 'Av. Zoilo Rodríguez, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.hoteles,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/sonestaloja.com'
  },
  {
    name: 'Mercado Centro Comercial',
    slug: 'mercado-centro-comercial',
    description: 'Mercado tradicional',
    content: 'Mercado tradicional con productos frescos, comida típica y artesanías locales. Ambiente auténtico.',
    phone: '07-257-0407',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: '10 de Agosto y 18 de Noviembre',
    lat: -3.9972,
    lng: -79.2045,
    address: '10 de Agosto y 18 de Noviembre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.mercados,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Mercado Mayorista',
    slug: 'mercado-mayorista',
    description: 'Mercado de distribución',
    content: 'Mercado mayorista para distribución de productos a nivel regional. Venta al por mayor y minorista.',
    phone: '07-257-0000',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Av. Nueva Loja',
    lat: -3.9815,
    lng: -79.2155,
    address: 'Av. Nueva Loja, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.mercados,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Cruz Roja Ecuatoriana Loja',
    slug: 'cruz-roja-ecuatoriana-loja',
    description: 'Cruz Roja local',
    content: 'Institución humanitaria con servicios de emergencia, primeros auxilios y programas sociales.',
    phone: '07-257-0200',
    email: null,
    website: 'https://www.cruzroja.org.ec/',
    location: 'Av. Universitaria y Quito',
    lat: -3.9915,
    lng: -79.2045,
    address: 'Av. Universitaria y Quito, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/cruzroja.org.ec'
  },
  {
    name: 'Pío Pío Loja',
    slug: 'pio-pio-loja',
    description: 'Restaurante de pollo',
    content: 'Restaurante especializado en pollo frito y asado. Comida rápida familiar con delivery.',
    phone: '07-257-6666',
    email: null,
    website: 'https://www.piopio.com.ec/',
    location: 'Av. Universitaria y Mercadillo',
    lat: -3.9985,
    lng: -79.2038,
    address: 'Av. Universitaria y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.restaurantes, // Restaurantes existente
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/piopio.com.ec'
  },
  {
    name: 'Parque Recreacional Jipiro',
    slug: 'parque-recreacional-jipiro',
    description: 'Parque recreativo principal',
    content: 'Parque con lagos, juegos infantiles, áreas deportivas y espacios para picnic. Ideal para familias.',
    phone: '07-257-0407',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Av. Salvador Bustamante Celi',
    lat: -3.9745,
    lng: -79.2015,
    address: 'Av. Salvador Bustamante Celi, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.recreacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Zoológico Municipal',
    slug: 'zoologico-municipal',
    description: 'Zoológico local',
    content: 'Zoológico con variedad de especies animales nativas y exóticas. Programas educativos y conservación.',
    phone: '07-257-0407',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Av. Orillas del Zamora',
    lat: -3.9655,
    lng: -79.2015,
    address: 'Av. Orillas del Zamora, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.recreacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Museo de la Música',
    slug: 'museo-de-la-musica',
    description: 'Museo temático musical',
    content: 'Museo dedicado a la historia musical de Loja. Instrumentos históricos y exposiciones interactivas.',
    phone: '07-257-2222',
    email: null,
    website: 'https://www.loja.gob.ec/',
    location: 'Bernardo Valdivieso y Rocafuerte',
    lat: -3.9981,
    lng: -79.2028,
    address: 'Bernardo Valdivieso y Rocafuerte, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cultura,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/loja.gob.ec'
  },
  {
    name: 'Cáritas Loja',
    slug: 'caritas-loja',
    description: 'Organización benéfica',
    content: 'Organización sin fines de lucro dedicada a programas sociales, ayuda humanitaria y desarrollo comunitario.',
    phone: '07-257-1111',
    email: null,
    website: 'https://www.diocesisdeloja.org/',
    location: 'Bernardo Valdivieso y Rocafuerte',
    lat: -3.9985,
    lng: -79.2035,
    address: 'Bernardo Valdivieso y Rocafuerte, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.ong,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/diocesisdeloja.org'
  },
  {
    name: 'Heladería La Tienda',
    slug: 'heladeria-la-tienda',
    description: 'Heladería tradicional',
    content: 'Heladería con sabores tradicionales y artesanales. Postres caseros y bebidas frías.',
    phone: '07-257-8888',
    email: null,
    website: 'https://www.facebook.com/HeladeriaLaTiendaLoja/',
    location: 'Bolívar y 10 de Agosto',
    lat: -3.9972,
    lng: -79.2042,
    address: 'Bolívar y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.alimentos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=La+Tienda&background=F57F17&color=fff'
  },
  {
    name: 'Puerta de la Ciudad',
    slug: 'puerta-de-la-ciudad',
    description: 'Monumento turístico',
    content: 'Monumento emblemático de la ciudad, punto de referencia histórica y turística. Visita obligatoria.',
    phone: '07-257-0407',
    email: null,
    website: 'https://lojaecuador.com.ec/',
    location: 'Av. Gran Colombia',
    lat: -3.9880,
    lng: -79.2025,
    address: 'Av. Gran Colombia, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.turismo,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/lojaecuador.com.ec'
  }
]

async function importBusinesses() {
  console.log('Importando negocios...')
  
  try {
    let importedCount = 0
    let skippedCount = 0
    
    for (const business of businesses) {
      // Verificar si ya existe
      const existing = await prisma.venue.findFirst({
        where: {
          OR: [
            { slug: business.slug },
            { name: business.name }
          ]
        }
      })
      
      if (existing) {
        console.log(`⚠️  El negocio "${business.name}" ya existe, omitiendo...`)
        skippedCount++
        continue
      }
      
      // Crear el negocio
      const created = await prisma.venue.create({
        data: business
      })
      
      console.log(`✅ Negocio "${business.name}" importado con ID: ${created.id}`)
      importedCount++
    }
    
    console.log(`\n🎉 Importación completada!`)
    console.log(`📊 Resumen:`)
    console.log(`   - Importados: ${importedCount}`)
    console.log(`   - Omitidos: ${skippedCount}`)
    console.log(`   - Total procesados: ${importedCount + skippedCount}`)
    
  } catch (error) {
    console.error('❌ Error durante la importación:', error)
  } finally {
    await prisma.$disconnect()
  }
}

importBusinesses()
