import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// IDs de las categorías creadas
const categoryIds = {
  tradicional: 'cmlywftw10000yk8zluldb77c',
  cafe: 'cmlywfu5p0001yk8zqmsfdeva',
  parrillas: 'cmlywfubc0002yk8zyhnh7w3g',
  internacional: 'cmlywfugy0003yk8z5002qhnx',
  rapida: 'cmlywfumo0004yk8z0gdxi3zm',
  bares: 'cmlywfusb0005yk8zk4jml2gb',
  mariscos: 'cmlywfuxy0006yk8ze436w5c2'
}

const restaurants = [
  {
    name: 'Mama Lola',
    slug: 'mama-lola',
    description: 'Restaurante tradicional lojano',
    content: 'Especializado en comida tradicional lojana con platos típicos de la región',
    phone: '07-257-8854',
    email: null,
    website: 'https://lojaecuador.com.ec/restaurante-mama-lola/',
    location: 'Av. Salvador Bustamante Celi',
    lat: -3.9808,
    lng: -79.2018,
    address: 'Av. Salvador Bustamante Celi',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/03/mama-lola-loja.jpg'
  },
  {
    name: 'Salón Lolita',
    slug: 'salon-lolita',
    description: 'Restaurante tradicional con ambiente clásico',
    content: 'Especializado en platos tradicionales lojanos en un ambiente acogedor',
    phone: '07-257-1234',
    email: null,
    website: 'https://lojaecuador.com.ec/portfolio/salon-lolita/',
    location: 'Olmedo y Rocafuerte',
    lat: -3.9895,
    lng: -79.2023,
    address: 'Olmedo y Rocafuerte',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/salon-lolita-comida.jpg'
  },
  {
    name: 'Wasi Kaphiy',
    slug: 'wasi-kaphiy',
    description: 'Cafetería con especialidades locales',
    content: 'Café acogedor con especialidades de café local y repostería artesanal',
    phone: '098-765-4321',
    email: null,
    website: 'https://lojaecuador.com.ec/portfolio/wasi-kaphiy/',
    location: 'Calle Lourdes entre 24 de Mayo',
    lat: -3.9912,
    lng: -79.2051,
    address: 'Calle Lourdes entre 24 de Mayo',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafe,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/wasi-kaphiy-cafe.jpg'
  },
  {
    name: 'El Tamal Lojano',
    slug: 'el-tamal-lojano',
    description: 'Especialistas en tamales lojanos',
    content: 'Tradicional restaurante especializado en tamales y platos típicos de Loja',
    phone: '07-257-0138',
    email: null,
    website: 'https://www.facebook.com/eltamallojano/',
    location: '18 de Noviembre e Imbabura',
    lat: -3.9968,
    lng: -79.2045,
    address: '18 de Noviembre e Imbabura',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/18258273_nNf1N_YmQ.jpg'
  },
  {
    name: 'La Huerta Brewpub',
    slug: 'la-huerta-brewpub',
    description: 'Cervecería artesanal con comida',
    content: 'Cervecería artesanal con carta de comida y ambiente moderno',
    phone: '099-123-4567',
    email: null,
    website: 'https://www.facebook.com/lahuertabrewpub/',
    location: 'Calle Lourdes 14-80',
    lat: -3.9995,
    lng: -79.2062,
    address: 'Calle Lourdes 14-80',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.bares,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/51239564_4mO6.jpg'
  },
  {
    name: 'Origen Restaurant',
    slug: 'origen-restaurant',
    description: 'Restaurante de autor con cocina fusión',
    content: 'Restaurante contemporáneo con platos de autor y cocina de fusión',
    phone: '098-445-5667',
    email: null,
    website: 'https://lojaecuador.com.ec/restaurant-el-origen/',
    location: 'Av. Manuel Agustín Aguirre',
    lat: -4.0251,
    lng: -79.2015,
    address: 'Av. Manuel Agustín Aguirre',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/origen-restaurant.jpg'
  },
  {
    name: 'Rincón de Borgoña',
    slug: 'rincon-de-borgona',
    description: 'Restaurante con especialidades locales',
    content: 'Acogedor restaurante especializado en platos tradicionales con toque moderno',
    phone: '07-258-4567',
    email: null,
    website: 'https://lojaecuador.com.ec/portfolio/rincon-de-borgona/',
    location: 'Juan J. Peña y Rocafuerte',
    lat: -3.9855,
    lng: -79.2032,
    address: 'Juan J. Peña y Rocafuerte',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/rincon-borgona.jpg'
  },
  {
    name: 'Forno di Fango',
    slug: 'forno-di-fango',
    description: 'Restaurante italiano especializado en pizzas',
    content: 'Auténtica cocina italiana con especialidad en pizzas hechas en horno de leña',
    phone: '099-887-7665',
    email: null,
    website: 'https://www.instagram.com/fornodifango/',
    location: 'Calle Miguel Riofrio',
    lat: -3.9942,
    lng: -79.2075,
    address: 'Calle Miguel Riofrio',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/583921_LzR.jpg'
  },
  {
    name: 'VidaVentura',
    slug: 'vidaventura',
    description: 'Restaurante con vista panorámica',
    content: 'Restaurante con vistas panorámicas de la ciudad y carta variada',
    phone: '07-258-9000',
    email: null,
    website: 'https://www.facebook.com/vidaventuraloja/',
    location: 'Av. Zoilo Rodríguez',
    lat: -3.9935,
    lng: -79.1978,
    address: 'Av. Zoilo Rodríguez',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/123456_vidav.jpg'
  },
  {
    name: 'La Buona Pasta',
    slug: 'la-buona-pasta',
    description: 'Especialistas en pasta italiana',
    content: 'Restaurante italiano especializado en pasta fresca y platos tradicionales',
    phone: '07-256-7890',
    email: null,
    website: 'https://www.facebook.com/labuonapastaloja/',
    location: 'Calle 24 de Mayo',
    lat: -3.9975,
    lng: -79.2031,
    address: 'Calle 24 de Mayo',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/321654_pasta.jpg'
  },
  {
    name: 'Riscomar',
    slug: 'riscomar',
    description: 'Especialistas en mariscos',
    content: 'Restaurante especializado en mariscos frescos y pescado',
    phone: '07-257-3344',
    email: null,
    website: 'https://www.facebook.com/riscomarloja/',
    location: 'Bolívar y Catacocha',
    lat: -4.0012,
    lng: -79.2048,
    address: 'Bolívar y Catacocha',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.mariscos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/riscomar-seafood.jpg'
  },
  {
    name: 'Dumas',
    slug: 'dumas',
    description: 'Restaurante de alta cocina',
    content: 'Elegante restaurante especializado en alta cocina y platos gourmet',
    phone: '099-332-2110',
    email: null,
    website: 'https://www.facebook.com/dumasrestaurante/',
    location: 'Bernardo Valdivieso y Azuay',
    lat: -3.9982,
    lng: -79.2025,
    address: 'Bernardo Valdivieso y Azuay',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/789456_dumas.jpg'
  },
  {
    name: 'A lo Mero Mero',
    slug: 'a-lo-mero-mero',
    description: 'Comida mexicana tradicional',
    content: 'Restaurante especializado en comida mexicana auténtica',
    phone: '099-776-6554',
    email: null,
    website: 'https://www.facebook.com/alomero_mero/',
    location: 'Rocafuerte 15-20',
    lat: -3.9958,
    lng: -79.2012,
    address: 'Rocafuerte 15-20',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/654321_mex.jpg'
  },
  {
    name: 'Aquiles',
    slug: 'aquiles',
    description: 'Restaurante gourmet',
    content: 'Restaurante gourmet con platos de autor y vinos seleccionados',
    phone: '07-258-1122',
    email: null,
    website: 'https://www.facebook.com/aquilesrestaurante/',
    location: 'Calle Lourdes y Olmedo',
    lat: -4.0005,
    lng: -79.2038,
    address: 'Calle Lourdes y Olmedo',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/159753_aq.jpg'
  },
  {
    name: 'El Arca',
    slug: 'el-arca',
    description: 'Restaurante vegetariano',
    content: 'Restaurante especializado en cocina vegetariana y saludable',
    phone: '07-257-2233',
    email: null,
    website: 'https://lojaecuador.com.ec/portfolio/el-arca/',
    location: 'Av. Eduardo Kingman',
    lat: -3.9882,
    lng: -79.2015,
    address: 'Av. Eduardo Kingman',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/el-arca-loja.jpg'
  },
  {
    name: 'Tutto Fredo',
    slug: 'tutto-fredo',
    description: 'Heladería artesanal italiana',
    content: 'Heladería artesanal con sabores italianos tradicionales',
    phone: '07-257-4455',
    email: null,
    website: 'https://tuttofredo.com.ec/',
    location: 'Calle Bolívar',
    lat: -3.9972,
    lng: -79.2042,
    address: 'Calle Bolívar',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafe,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/03/tutto-fredo.jpg'
  },
  {
    name: 'Cafecito Lojano',
    slug: 'cafecito-lojano',
    description: 'Cafetería tradicional',
    content: 'Acogedora cafetería con café local y ambiente tradicional lojano',
    phone: '098-998-8776',
    email: null,
    website: 'https://lojaecuador.com.ec/portfolio/el-cafecito-lojano/',
    location: 'Calle Lourdes 15-12',
    lat: -3.9985,
    lng: -79.2035,
    address: 'Calle Lourdes 15-12',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafe,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/cafecito-lojano.jpg'
  },
  {
    name: 'Apetitto',
    slug: 'apetitto',
    description: 'Restaurante familiar',
    content: 'Restaurante familiar con carta variada y precios accesibles',
    phone: '07-257-6677',
    email: null,
    website: 'https://www.facebook.com/ApetittoLoja/',
    location: 'Calle Miguel Riofrío',
    lat: -3.9925,
    lng: -79.2068,
    address: 'Calle Miguel Riofrío',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/apetitto-restaurant.jpg'
  },
  {
    name: 'Oink Bar & Grill',
    slug: 'oink-bar-grill',
    description: 'Bar & Grill especializado en carnes',
    content: 'Bar & Grill con especialidad en carnes y hamburguesas artesanales',
    phone: '098-112-2334',
    email: null,
    website: 'https://www.facebook.com/OinkBarGrill/',
    location: 'Av. Orillas del Zamora',
    lat: -3.9915,
    lng: -79.2055,
    address: 'Av. Orillas del Zamora',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.parrillas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ktaxi.com.ec/wp-content/uploads/2023/11/oink-loja.jpg'
  },
  {
    name: 'Picantería Terraza',
    slug: 'picanteria-terraza',
    description: 'Picantería tradicional lojana',
    content: 'Tradicional picantería lojana con platos típicos y ambiente familiar',
    phone: '07-258-0099',
    email: null,
    website: 'https://www.facebook.com/picanteriaterraza/',
    location: 'Mercadillo y 18 de Noviembre',
    lat: -4.0052,
    lng: -79.2028,
    address: 'Mercadillo y 18 de Noviembre',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/picanteria-terraza.jpg'
  },
  {
    name: 'Carbonero',
    slug: 'carbonero',
    description: 'Especialistas en parrilladas',
    content: 'Restaurante especializado en carnes a la parrilla y asados tradicionales',
    phone: '099-445-5660',
    email: null,
    website: 'https://www.facebook.com/CarboneroLoja/',
    location: 'Av. Salvador Bustamante Celi',
    lat: -3.9825,
    lng: -79.2008,
    address: 'Av. Salvador Bustamante Celi',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.parrillas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/carbon.jpg'
  },
  {
    name: 'Cabaña del Río',
    slug: 'cabana-del-rio',
    description: 'Restaurante campestre',
    content: 'Restaurante campestre con vistas al río y ambiente natural',
    phone: '07-257-0011',
    email: null,
    website: 'https://www.facebook.com/cabana_rio/',
    location: 'Valle de Jipiro',
    lat: -3.9750,
    lng: -79.2105,
    address: 'Valle de Jipiro',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/cabana-rio.jpg'
  },
  {
    name: 'Parrilladas El Gaucho',
    slug: 'parrilladas-el-gaucho',
    description: 'Especialistas en carne argentina',
    content: 'Restaurante especializado en cortes argentinos y parrilladas tradicionales',
    phone: '07-258-1212',
    email: null,
    website: 'https://www.facebook.com/elgaucho/',
    location: 'Av. Eduardo Kingman',
    lat: -3.9890,
    lng: -79.2010,
    address: 'Av. Eduardo Kingman',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.parrillas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/gaucho.jpg'
  },
  {
    name: 'Manila',
    slug: 'manila',
    description: 'Comida filipina',
    content: 'Restaurante especializado en cocina filipina tradicional',
    phone: '07-257-3311',
    email: null,
    website: 'https://www.facebook.com/RestauranteManila/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9960,
    lng: -79.2040,
    address: '10 de Agosto y Bernardo Valdivieso',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/restaurante-manila.jpg'
  },
  {
    name: 'Berna Cafetería',
    slug: 'berna-cafeteria',
    description: 'Cafetería suiza',
    content: 'Cafetería con influencia suiza y especialidades en café',
    phone: '07-256-4400',
    email: null,
    website: 'https://www.facebook.com/CafeteriaBerna/',
    location: 'José Antonio Eguiguren',
    lat: -3.9978,
    lng: -79.2038,
    address: 'José Antonio Eguiguren',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafe,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/cafeteria-berna.jpg'
  },
  {
    name: 'Le Rendez-vous',
    slug: 'le-rendez-vous',
    description: 'Restaurante francés',
    content: 'Elegante restaurante francés con cocina tradicional gala',
    phone: '099-223-3445',
    email: null,
    website: 'https://www.facebook.com/lerendezvous/',
    location: 'Lourdes y Sucre',
    lat: -4.0025,
    lng: -79.2052,
    address: 'Lourdes y Sucre',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/rendezvous.jpg'
  },
  {
    name: 'Burger Chariot',
    slug: 'burger-chariot',
    description: 'Hamburguesería gourmet',
    content: 'Hamburguesería gourmet con hamburguesas artesanales y ingredientes premium',
    phone: '098-556-6778',
    email: null,
    website: 'https://www.facebook.com/BurgerChariot/',
    location: 'Miguel Riofrío e Universitaria',
    lat: -3.9945,
    lng: -79.2085,
    address: 'Miguel Riofrío e Universitaria',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.rapida,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/burger-chariot.jpg'
  },
  {
    name: 'Plaza Inn',
    slug: 'plaza-inn',
    description: 'Restaurante de buffet',
    content: 'Restaurante con servicio de buffet y carta variada',
    phone: '07-257-9988',
    email: null,
    website: 'https://www.facebook.com/PlazaInnLoja/',
    location: 'Bernardo Valdivieso y Colón',
    lat: -3.9970,
    lng: -79.2045,
    address: 'Bernardo Valdivieso y Colón',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.tradicional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://images.minube.com/plazainn.jpg'
  },
  {
    name: 'Eólico Villonaco',
    slug: 'eolico-villonaco',
    description: 'Restaurante con vistas panorámicas',
    content: 'Restaurante ubicado en el parque eólico con vistas espectaculares',
    phone: null,
    email: null,
    website: 'https://lojaecuador.com.ec/turismo-en-loja-guia-completa/',
    location: 'Vía a Catamayo',
    lat: -3.9955,
    lng: -79.2645,
    address: 'Vía a Catamayo',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://lojaecuador.com.ec/wp-content/uploads/2023/05/eolico-villonaco.jpg'
  },
  {
    name: 'Topoli',
    slug: 'topoli',
    description: 'Restaurante mediterráneo',
    content: 'Restaurante especializado en cocina mediterránea y platos saludables',
    phone: '07-257-1122',
    email: null,
    website: 'https://www.facebook.com/TopoliLoja/',
    location: 'Rocafuerte y Bolívar',
    lat: -3.9980,
    lng: -79.2030,
    address: 'Rocafuerte y Bolívar',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.internacional,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://fastly.4sqi.net/img/general/600x600/topoli.jpg'
  }
]

async function importRestaurants() {
  console.log('Importando restaurantes...')
  
  try {
    let importedCount = 0
    let skippedCount = 0
    
    for (const restaurant of restaurants) {
      // Verificar si ya existe
      const existing = await prisma.venue.findFirst({
        where: {
          OR: [
            { slug: restaurant.slug },
            { name: restaurant.name }
          ]
        }
      })
      
      if (existing) {
        console.log(`⚠️  El restaurante "${restaurant.name}" ya existe, omitiendo...`)
        skippedCount++
        continue
      }
      
      // Crear el restaurante
      const created = await prisma.venue.create({
        data: restaurant
      })
      
      console.log(`✅ Restaurante "${restaurant.name}" importado con ID: ${created.id}`)
      importedCount++
    }
    
    console.log(`\n🎉 Importación completada!`)
    console.log(`📊 Resumen:`)
    console.log(`   - Importados: ${importedCount}`)
    console.log(`   - Omitidos: ${skippedCount}`)
    console.log(`   - Total procesados: ${importedCount + skippedCount}`)
    
  } catch (error) {
    console.error('❌ Error durante la importación:', error)
  } finally {
    await prisma.$disconnect()
  }
}

importRestaurants()
