import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// IDs de las categorías existentes y nuevas
const categoryIds = {
  hoteles: 'cmlt9wcfa000acdlokrf7yq7b', // Hoteles existente
  restaurantes: 'cmlt9wbbb0007cdlo7zxchmmv', // Restaurantes existente
  cafeteria: 'cmlywfu5p0001yk8zqmsfdeva', // Café y Repostería existente
  alimentos: 'cmlywtffg000iru70znqov0xg', // Alimentos y Bebidas existente
  moda: 'cmlyx139n000013osel18okgo', // Moda y Ropa (nueva)
  electrodomesticos: 'cmlyx13i2000113osggf1qict', // Electrodomésticos y Tecnología (nueva)
  calzado: 'cmlyx13nr000213osqa7j7bqx', // Calzado y Accesorios (nueva)
  finanzas: 'cmlywtct60002ru700zopo7jy', // Bancos y Finanzas existente
  salud: 'cmlywtcnh0001ru70n1qf0uwl', // Salud y Medicina existente
  educacion: 'cmlyx14ag000613osojmvn0yq', // Centros Educativos Privados (nueva)
  deportes: 'cmlywte5n000aru70jqolg6hi', // Deportes y Fitness existente
  vehiculos: 'cmlywtebb000bru70alq0x0sd', // Vehículos y Automotores existente
  funerarias: 'cmlyx13te000313os7wrcr0lm', // Funerarias y Servicios Fúnebres (nueva)
  servicios: 'cmlywtdoj0007ru70s2cw5gx2', // Servicios Públicos existente
  legales: 'cmlyx13z3000413osgkv44tbj', // Notarías y Servicios Legales (nueva)
  flores: 'cmlyx144r000513os994k1v84', // Flores y Regalos (nueva)
  centrosMedicos: 'cmlyx14g8000713osdwns9pm7' // Centros Médicos Privados (nueva)
}

const businesses = [
  {
    name: 'Hotel Libertador',
    slug: 'hotel-libertador',
    description: 'Hotel céntrico con servicio completo',
    content: 'Hotel ubicado en el centro histórico de Loja con habitaciones confortables, restaurante y servicio de habitaciones.',
    phone: '07-257-0344',
    email: null,
    website: 'https://hotellibertador.com.ec/',
    location: 'Colón 14-30 y Sucre',
    lat: -3.9961,
    lng: -79.2038,
    address: 'Colón 14-30 y Sucre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.hoteles,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/hotellibertador.com.ec'
  },
  {
    name: 'Grand Victoria Boutique Hotel',
    slug: 'grand-victoria-boutique-hotel',
    description: 'Hotel boutique de lujo',
    content: 'Hotel boutique con diseño elegante, spa gourmet y atención personalizada. Experiencia de lujo en el corazón de Loja.',
    phone: '07-258-3500',
    email: null,
    website: 'https://grandvictoria.com.ec/',
    location: 'Bernardo Valdivieso y José Antonio Eguiguren',
    lat: -3.9970,
    lng: -79.2041,
    address: 'Bernardo Valdivieso y José Antonio Eguiguren, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.hoteles,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/grandvictoria.com.ec'
  },
  {
    name: 'Hotel Ramsés',
    slug: 'hotel-ramses',
    description: 'Hotel tradicional lojano',
    content: 'Hotel con historia y tradición, ubicado en el centro de la ciudad. Servicio cálido y habitaciones cómodas.',
    phone: '07-257-1402',
    email: null,
    website: 'https://www.facebook.com/hotelramsesloja/',
    location: 'Colón y Bolívar',
    lat: -3.9965,
    lng: -79.2030,
    address: 'Colón y Bolívar, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.hoteles,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Hotel+Ramsés&background=8B4513&color=fff'
  },
  {
    name: 'Hotel Quo Vadis',
    slug: 'hotel-quo-vadis',
    description: 'Hotel con encanto familiar',
    content: 'Hotel familiar con ambiente acogedor, ideal para estancias cortas y negocios. Ubicado cerca del terminal terrestre.',
    phone: '07-258-1805',
    email: null,
    website: 'https://www.facebook.com/hotelquovadisloja/',
    location: 'Av. Isidro Ayora y 8 de Diciembre',
    lat: -3.9801,
    lng: -79.2052,
    address: 'Av. Isidro Ayora y 8 de Diciembre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.hoteles,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Hotel+Quo+Vadis&background=2C3E50&color=fff'
  },
  {
    name: 'Pizzería Veni Vidi Vici',
    slug: 'pizzeria-veni-vidi-vici',
    description: 'Pizzería artesanal italiana',
    content: 'Auténtica pizzería italiana con masa madre, ingredientes importados y horno de leña. Ambiente romántico.',
    phone: '07-257-5205',
    email: null,
    website: 'https://www.facebook.com/venividiviciloja/',
    location: '24 de Mayo y Miguel Riofrío',
    lat: -3.9950,
    lng: -79.2061,
    address: '24 de Mayo y Miguel Riofrío, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.restaurantes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Veni+Vidi+Vici&background=DC143C&color=fff'
  },
  {
    name: 'El Rincón de la Abuela',
    slug: 'el-rincon-de-la-abuela',
    description: 'Comida casera tradicional',
    content: 'Restaurante especializado en comida casera tradicional lojana. Recetas de la abuela con ingredientes frescos.',
    phone: '098-765-4321',
    email: null,
    website: 'https://www.facebook.com/rincondelaabuelaloja/',
    location: 'Av. Orillas del Zamora y Guayaquil',
    lat: -3.9880,
    lng: -79.2015,
    address: 'Av. Orillas del Zamora y Guayaquil, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.restaurantes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Rincon+Abuela&background=FF6B6B&color=fff'
  },
  {
    name: 'Cevichería 200 Millas',
    slug: 'cevicheria-200-millas',
    description: 'Especialistas en mariscos',
    content: 'Cevichería especializada en mariscos frescos y pescados. Ceviches tradicionales y creativos.',
    phone: '07-257-8901',
    email: null,
    website: 'https://www.facebook.com/200millasloja/',
    location: '18 de Noviembre y Lourdes',
    lat: -4.0001,
    lng: -79.2033,
    address: '18 de Noviembre y Lourdes, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.restaurantes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=200+Millas&background=00BCD4&color=fff'
  },
  {
    name: 'Casa Lojana',
    slug: 'casa-lojana',
    description: 'Restaurante con vista panorámica',
    content: 'Restaurante con vista a la ciudad, especializado en comida tradicional lojana y platos gourmet.',
    phone: '07-258-7741',
    email: null,
    website: 'https://www.casalojana.com.ec/',
    location: 'Av. Salvador Bustamante Celi (Sector Jipiro)',
    lat: -3.9740,
    lng: -79.2010,
    address: 'Av. Salvador Bustamante Celi, Sector Jipiro, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.restaurantes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/casalojana.com.ec'
  },
  {
    name: 'Café Indura',
    slug: 'cafe-indura',
    description: 'Cafetería con ambiente bohemio',
    content: 'Cafetería con café de especialidad, postres artesanales y ambiente bohemio. Ideal para trabajar y socializar.',
    phone: '07-256-1122',
    email: null,
    website: 'https://www.facebook.com/cafeindura/',
    location: 'Rocafuerte y 24 de Mayo',
    lat: -3.9955,
    lng: -79.2044,
    address: 'Rocafuerte y 24 de Mayo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafeteria,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Café+Indura&background=795548&color=fff'
  },
  {
    name: 'Café de Roma',
    slug: 'cafe-de-roma',
    description: 'Cafetería italiana tradicional',
    content: 'Cafetería con estilo italiano, café espresso auténtico y deliciosos postres italianos.',
    phone: '07-258-0011',
    email: null,
    website: 'https://www.facebook.com/cafederoma/',
    location: 'Sucre y José Antonio Eguiguren',
    lat: -3.9960,
    lng: -79.2030,
    address: 'Sucre y José Antonio Eguiguren, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.cafeteria,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Café+Roma&background=8D6E63&color=fff'
  },
  {
    name: 'Pastelería D\'Marco',
    slug: 'pasteria-dmarco',
    description: 'Pastelería fina y repostería',
    content: 'Pastelería especializada en tortas, pasteles finos y repostería gourmet. Pedidos personalizados.',
    phone: '07-257-3344',
    email: null,
    website: 'https://www.facebook.com/pasteleriadmarco/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9965,
    lng: -79.2045,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.alimentos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=D\'Marco&background=E91E63&color=fff'
  },
  {
    name: 'Panadería El Pan Nuestro',
    slug: 'panaderia-el-pan-nuestro',
    description: 'Panadería artesanal tradicional',
    content: 'Panadería con pan fresco horneado diariamente, pasteles tradicionales y productos artesanales.',
    phone: '07-257-6688',
    email: null,
    website: 'https://www.facebook.com/elpannuestroloja/',
    location: 'Av. Universitaria y Mercadillo',
    lat: -3.9980,
    lng: -79.2035,
    address: 'Av. Universitaria y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.alimentos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=El+Pan+Nuestro&background=D84315&color=fff'
  },
  {
    name: 'ETAFASHION Loja',
    slug: 'etafashion-loja',
    description: 'Tienda de ropa de moda',
    content: 'Tienda de ropa con las últimas tendencias de moda. Marcas nacionales e importadas para hombre y mujer.',
    phone: '07-258-9999',
    email: null,
    website: 'https://www.etafashion.com/',
    location: 'Centro Comercial Don Daniel',
    lat: -3.9902,
    lng: -79.2051,
    address: 'Centro Comercial Don Daniel, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.moda,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/etafashion.com'
  },
  {
    name: 'RM Loja',
    slug: 'rm-loja',
    description: 'Tienda por departamento',
    content: 'Gran tienda por departamento con ropa, accesorios y artículos para el hogar. Marcas reconocidas.',
    phone: '07-258-7777',
    email: null,
    website: 'https://www.tiendasrm.com/',
    location: 'Av. Orillas del Zamora (Multiplaza)',
    lat: -3.9855,
    lng: -79.2010,
    address: 'Av. Orillas del Zamora, Multiplaza, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.moda,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/tiendasrm.com'
  },
  {
    name: 'Marcimex Loja',
    slug: 'marcimex-loja',
    description: 'Electrodomésticos y tecnología',
    content: 'Tienda especializada en electrodomésticos, tecnología y artículos para el hogar. Las mejores marcas.',
    phone: '07-257-5511',
    email: null,
    website: 'https://www.marcimex.com/',
    location: '10 de Agosto y 18 de Noviembre',
    lat: -3.9972,
    lng: -79.2045,
    address: '10 de Agosto y 18 de Noviembre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.electrodomesticos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/marcimex.com'
  },
  {
    name: 'Créditos Económicos Loja',
    slug: 'creditos-economicos-loja',
    description: 'Tienda de electrodomésticos a crédito',
    content: 'Tienda especializada en venta de electrodomésticos y tecnología a crédito. Opciones de financiamiento.',
    phone: '07-257-4433',
    email: null,
    website: 'https://www.creditoseconomicos.com/',
    location: 'Bolívar y Azuay',
    lat: -3.9975,
    lng: -79.2055,
    address: 'Bolívar y Azuay, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.electrodomesticos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/creditoseconomicos.com'
  },
  {
    name: 'Calzado Buestán',
    slug: 'calzado-buestan',
    description: 'Tienda de calzado de calidad',
    content: 'Tienda especializada en calzado de calidad para hombre, mujer y niños. Marcas reconocidas y modelos cómodos.',
    phone: '07-257-2299',
    email: null,
    website: 'https://buestan.com/',
    location: 'Sucre y 10 de Agosto',
    lat: -3.9955,
    lng: -79.2035,
    address: 'Sucre y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.calzado,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/buestan.com'
  },
  {
    name: 'Boutique Monalisa',
    slug: 'boutique-monalisa',
    description: 'Boutique de moda femenina',
    content: 'Boutique especializada en moda femenina, vestidos de gala y ropa de diseño. Atención personalizada.',
    phone: '099-112-2334',
    email: null,
    website: 'https://www.facebook.com/monalisaloja/',
    location: 'Bolívar y Mercadillo',
    lat: -3.9971,
    lng: -79.2021,
    address: 'Bolívar y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.moda,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Boutique+Monalisa&background=9C27B0&color=fff'
  },
  {
    name: 'Cooperativa JEP Loja',
    slug: 'cooperativa-jep-loja',
    description: 'Cooperativa de crédito y ahorro',
    content: 'Cooperativa financiera con servicios de crédito, ahorro e inversión. Atención personalizada a socios.',
    phone: '07-258-2222',
    email: null,
    website: 'https://www.coopjep.fin.ec/',
    location: '18 de Noviembre y 10 de Agosto',
    lat: -3.9970,
    lng: -79.2048,
    address: '18 de Noviembre y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/coopjep.fin.ec'
  },
  {
    name: 'Banco Pichincha Loja',
    slug: 'banco-pichincha-loja',
    description: 'Banco líder nacional',
    content: 'Sucursal del banco más grande del Ecuador. Servicios bancarios completos para personas y empresas.',
    phone: '07-257-0100',
    email: null,
    website: 'https://www.pichincha.com/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9968,
    lng: -79.2042,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/pichincha.com'
  },
  {
    name: 'Banco Guayaquil Loja',
    slug: 'banco-guayaquil-loja',
    description: 'Banco con servicios integrales',
    content: 'Banco con amplia gama de servicios financieros, tarjetas de crédito y préstamos hipotecarios.',
    phone: '07-257-1155',
    email: null,
    website: 'https://www.bancoguayaquil.com/',
    location: 'Bolívar y José Antonio Eguiguren',
    lat: -3.9973,
    lng: -79.2037,
    address: 'Bolívar y José Antonio Eguiguren, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/bancoguayaquil.com'
  },
  {
    name: 'Mutualista Pichincha Loja',
    slug: 'mutualista-pichincha-loja',
    description: 'Seguros y servicios financieros',
    content: 'Institución financiera especializada en seguros, inversiones y servicios de previsión social.',
    phone: '07-258-3311',
    email: null,
    website: 'https://www.mutualistapichincha.com/',
    location: 'Rocafuerte y Sucre',
    lat: -3.9961,
    lng: -79.2025,
    address: 'Rocafuerte y Sucre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.finanzas,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/mutualistapichincha.com'
  },
  {
    name: 'Clínica Nataly',
    slug: 'clinica-nataly',
    description: 'Clínica médica privada',
    content: 'Clínica privada con servicios de consulta general, especialidades y laboratorio clínico.',
    phone: '07-257-1234',
    email: null,
    website: 'https://www.clinicanataly.com.ec/',
    location: 'Av. Universitaria y Catacocha',
    lat: -4.0025,
    lng: -79.2045,
    address: 'Av. Universitaria y Catacocha, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.centrosMedicos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/clinicanataly.com.ec'
  },
  {
    name: 'Hospital Clínica San José',
    slug: 'hospital-clinica-san-jose',
    description: 'Hospital privado con especialidades',
    content: 'Hospital privado con servicios de cirugía, maternidad, pediatría y especialidades médicas.',
    phone: '07-258-4455',
    email: null,
    website: 'https://www.facebook.com/clinicasanjoseloja/',
    location: 'Sucre y Quito',
    lat: -3.9915,
    lng: -79.2050,
    address: 'Sucre y Quito, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.centrosMedicos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Clinica+San+José&background=F44336&color=fff'
  },
  {
    name: 'Centro Médico Medilab',
    slug: 'centro-medico-medilab',
    description: 'Laboratorio clínico y consultorios',
    content: 'Centro médico con laboratorio clínico, consultorios médicos y servicios de diagnóstico.',
    phone: '07-257-9988',
    email: null,
    website: 'https://www.medilab.com.ec/',
    location: '18 de Noviembre y Mercadillo',
    lat: -3.9985,
    lng: -79.2032,
    address: '18 de Noviembre y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.centrosMedicos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/medilab.com.ec'
  },
  {
    name: 'Farmacias Económicas Loja',
    slug: 'farmacias-economicas-loja',
    description: 'Cadena de farmacias con precios bajos',
    content: 'Cadena de farmacias con medicamentos a precios económicos, productos de salud y atención farmacéutica.',
    phone: '07-258-6655',
    email: null,
    website: 'https://www.farmaciaseconomicas.com.ec/',
    location: 'Bolívar y Lourdes',
    lat: -4.0005,
    lng: -79.2038,
    address: 'Bolívar y Lourdes, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/farmaciaseconomicas.com.ec'
  },
  {
    name: 'Cruz Azul Loja',
    slug: 'cruz-azul-loja',
    description: 'Farmacia con servicio 24/7',
    content: 'Farmacia con servicio de emergencia 24 horas, medicamentos y productos farmacéuticos.',
    phone: '07-257-7744',
    email: null,
    website: 'https://www.farmaciascruzazul.com/',
    location: 'Av. Pío Jaramillo y Mercadillo',
    lat: -4.0155,
    lng: -79.2040,
    address: 'Av. Pío Jaramillo y Mercadillo, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.salud,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/farmaciascruzazul.com'
  },
  {
    name: 'Colegio San Francisco de Asís',
    slug: 'colegio-san-francisco-de-asis',
    description: 'Colegio católico tradicional',
    content: 'Colegio católico con educación de calidad, valores humanos y excelencia académica desde primaria hasta bachillerato.',
    phone: '07-257-0233',
    email: null,
    website: 'https://www.sanfranciscoloja.edu.ec/',
    location: 'Bolívar y Rocafuerte',
    lat: -3.9980,
    lng: -79.2020,
    address: 'Bolívar y Rocafuerte, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/sanfranciscoloja.edu.ec'
  },
  {
    name: 'Unidad Educativa La Inmaculada',
    slug: 'unidad-educativa-la-inmaculada',
    description: 'Colegio privado mixto',
    content: 'Unidad educativa privada con educación integral, bilingüe y programas de excelencia académica.',
    phone: '07-257-1122',
    email: null,
    website: 'https://www.inmaculadaloja.edu.ec/',
    location: 'Bernardo Valdivieso y 10 de Agosto',
    lat: -3.9965,
    lng: -79.2045,
    address: 'Bernardo Valdivieso y 10 de Agosto, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/inmaculadaloja.edu.ec'
  },
  {
    name: 'Instituto Tecnológico Sudamericano',
    slug: 'instituto-tecnologico-sudamericano',
    description: 'Instituto técnico superior',
    content: 'Instituto con carreras técnicas y tecnológicas, formación profesional y certificaciones industriales.',
    phone: '07-258-5544',
    email: null,
    website: 'https://www.sudamericano.edu.ec/',
    location: 'Mercadillo y Juan José Peña',
    lat: -3.9995,
    lng: -79.2025,
    address: 'Mercadillo y Juan José Peña, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/sudamericano.edu.ec'
  },
  {
    name: 'Alianza Francesa Loja',
    slug: 'alianza-francesa-loja',
    description: 'Centro de idiomas y cultura francesa',
    content: 'Centro especializado en enseñanza del francés, cultura francesa y certificaciones internacionales.',
    phone: '07-257-0111',
    email: null,
    website: 'https://www.afloja.org.ec/',
    location: '10 de Agosto y Bernardo Valdivieso',
    lat: -3.9968,
    lng: -79.2040,
    address: '10 de Agosto y Bernardo Valdivieso, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.educacion,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/afloja.org.ec'
  },
  {
    name: 'Taurus Gym',
    slug: 'taurus-gym',
    description: 'Gimnasio con equipamiento moderno',
    content: 'Gimnasio con equipamiento de última generación, clases grupales y entrenadores personales certificados.',
    phone: '098-445-5667',
    email: null,
    website: 'https://www.facebook.com/taurusgymloja/',
    location: 'Av. Universitaria y Lourdes',
    lat: -4.0001,
    lng: -79.2035,
    address: 'Av. Universitaria y Lourdes, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.deportes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Taurus+Gym&background=FF5722&color=fff'
  },
  {
    name: 'Megafit Loja',
    slug: 'megafit-loja',
    description: 'Centro de fitness y bienestar',
    content: 'Centro de fitness con programas de entrenamiento, nutrición y bienestar integral. Clases variadas.',
    phone: '099-332-1144',
    email: null,
    website: 'https://www.facebook.com/megafitloja/',
    location: 'Av. Emiliano Ortega y Lourdes',
    lat: -3.9995,
    lng: -79.2015,
    address: 'Av. Emiliano Ortega y Lourdes, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.deportes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Megafit+Loja&background=4CAF50&color=fff'
  },
  {
    name: 'Canchas Sintéticas El Balón',
    slug: 'canchas-sinteticas-el-balon',
    description: 'Complejo deportivo con canchas sintéticas',
    content: 'Complejo deportivo con canchas de fútbol sintético, fútbol sala y básquet. Alquiler por horas.',
    phone: '098-998-8776',
    email: null,
    website: 'https://www.facebook.com/elbalonloja/',
    location: 'Vía a Vilcabamba (Sector Punzara)',
    lat: -4.0355,
    lng: -79.2085,
    address: 'Vía a Vilcabamba, Sector Punzara, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.deportes,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=El+Balón&background=2196F3&color=fff'
  },
  {
    name: 'Toyocosta Loja (Toyota)',
    slug: 'toyocosta-loja',
    description: 'Concesionario oficial Toyota',
    content: 'Concesionario oficial Toyota con vehículos nuevos, seminuevos, servicio técnico y repuestos originales.',
    phone: '07-257-8899',
    email: null,
    website: 'https://www.toyocosta.com.ec/',
    location: 'Av. Cuxibamba y Zaruma',
    lat: -3.9815,
    lng: -79.2050,
    address: 'Av. Cuxibamba y Zaruma, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.vehiculos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/toyocosta.com.ec'
  },
  {
    name: 'Casabaca Loja',
    slug: 'casabaca-loja',
    description: 'Concesionario de vehículos múltiples marcas',
    content: 'Concesionario con vehículos de diversas marcas, financiamiento y servicio de mantenimiento completo.',
    phone: '07-258-6633',
    email: null,
    website: 'https://www.casabaca.com/',
    location: 'Av. 8 de Diciembre y Jipiro',
    lat: -3.9755,
    lng: -79.2045,
    address: 'Av. 8 de Diciembre y Jipiro, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.vehiculos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/casabaca.com'
  },
  {
    name: 'Lojacar',
    slug: 'lojacar',
    description: 'Agencia de vehículos seminuevos',
    content: 'Agencia especializada en vehículos seminuevos, compra-venta y financiamiento de autos.',
    phone: '07-258-1155',
    email: null,
    website: 'https://www.lojacar.com.ec/',
    location: 'Av. de los Paltas',
    lat: -4.0185,
    lng: -79.2155,
    address: 'Av. de los Paltas, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.vehiculos,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/lojacar.com.ec'
  },
  {
    name: 'Funeraria Jaramillo',
    slug: 'funeraria-jaramillo',
    description: 'Servicios funerarios completos',
    content: 'Funeraria con servicios completos, salas de velación, traslados y acompañamiento familiar.',
    phone: '07-257-0102',
    email: null,
    website: 'https://www.funerariajaramillo.com.ec/',
    location: 'Andrés Bello y 8 de Diciembre',
    lat: -3.9850,
    lng: -79.2040,
    address: 'Andrés Bello y 8 de Diciembre, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.funerarias,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://logo.clearbit.com/funerariajaramillo.com.ec'
  },
  {
    name: 'Notaría Segunda del Cantón Loja',
    slug: 'notaria-segunda-canton-loja',
    description: 'Servicios notariales y legales',
    content: 'Notaría con servicios de legalización de documentos, testamentos, poderes y asesoría legal.',
    phone: '07-257-4411',
    email: null,
    website: 'https://www.facebook.com/NotariaSegundaLoja/',
    location: 'Sucre y José Antonio Eguiguren',
    lat: -3.9960,
    lng: -79.2030,
    address: 'Sucre y José Antonio Eguiguren, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.legales,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Notaria+Segunda&background=607D8B&color=fff'
  },
  {
    name: 'Florería El Paraíso',
    slug: 'floreria-el-paraiso',
    description: 'Arreglos florales y regalos',
    content: 'Florería con arreglos florales personalizados, ramos, coronas y detalles para toda ocasión.',
    phone: '098-554-4332',
    email: null,
    website: 'https://www.facebook.com/elparaisoflorerialoja/',
    location: '18 de Noviembre y Azuay',
    lat: -4.0010,
    lng: -79.2042,
    address: '18 de Noviembre y Azuay, Loja',
    status: 'APPROVED' as const,
    featured: false,
    categoryId: categoryIds.flores,
    userId: 'cmlys6wkp00012wj6vicazyzh',
    googlePlaceId: null,
    image: 'https://ui-avatars.com/api/?name=Florería+El+Paraíso&background=4CAF50&color=fff'
  }
]

async function importAdditionalBusinesses() {
  console.log('Importando negocios adicionales...')
  
  try {
    let importedCount = 0
    let skippedCount = 0
    
    for (const business of businesses) {
      // Verificar si ya existe
      const existing = await prisma.venue.findFirst({
        where: {
          OR: [
            { slug: business.slug },
            { name: business.name }
          ]
        }
      })
      
      if (existing) {
        console.log(`⚠️  El negocio "${business.name}" ya existe, omitiendo...`)
        skippedCount++
        continue
      }
      
      // Crear el negocio
      const created = await prisma.venue.create({
        data: business
      })
      
      console.log(`✅ Negocio "${business.name}" importado con ID: ${created.id}`)
      importedCount++
    }
    
    console.log(`\n🎉 Importación completada!`)
    console.log(`📊 Resumen:`)
    console.log(`   - Importados: ${importedCount}`)
    console.log(`   - Omitidos: ${skippedCount}`)
    console.log(`   - Total procesados: ${importedCount + skippedCount}`)
    
  } catch (error) {
    console.error('❌ Error durante la importación:', error)
  } finally {
    await prisma.$disconnect()
  }
}

importAdditionalBusinesses()
