import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage } from '@/components/legal/legal-page'
export const metadata: Metadata = { title: 'Términos y condiciones — Vive Loja', alternates: { canonical: 'https://viveloja.com/terminos' } }
export default function TermsPage() { return <LegalPage eyebrow="Acuerdo de uso" title="Términos y condiciones" summary="Estas reglas explican cómo puedes usar Vive Loja, publicar contenido, reclamar negocios y contratar planes o extras.">
  <section><h2>1. Aceptación y alcance</h2><p>Al crear una cuenta, usar la plataforma o confirmar una contratación aceptas estos términos y las políticas vinculadas. Si actúas por un negocio, declaras tener autoridad suficiente para representarlo.</p></section>
  <section><h2>2. Cuenta y seguridad</h2><p>Debes proporcionar información correcta, mantener tus credenciales seguras y notificarnos si detectas acceso no autorizado. Eres responsable de la actividad realizada desde tu cuenta, salvo que la ley disponga otra cosa.</p></section>
  <section><h2>3. Directorio y contenido</h2><p>Vive Loja funciona como directorio y plataforma de promoción local. La información puede provenir de usuarios, fuentes públicas o proveedores externos. No garantizamos que horarios, precios, disponibilidad o datos de terceros permanezcan siempre actualizados.</p><p>Conservas los derechos sobre el contenido que publicas y nos concedes una licencia no exclusiva, mundial y gratuita para alojarlo, adaptarlo técnicamente, mostrarlo y promocionarlo dentro de la operación de Vive Loja.</p></section>
  <section><h2>4. Reclamos de negocios</h2><p>Solo puedes reclamar un negocio si eres su propietario, representante autorizado o puedes demostrar una relación legítima. Podemos solicitar correo, teléfono, documentos, fotografías u otra evidencia; también podemos rechazar, revocar o transferir la administración cuando la evidencia no sea suficiente.</p><p><strong>Presentar un reclamo falso, suplantar al titular o aportar evidencia manipulada está prohibido.</strong> Podemos suspender la cuenta, retirar el acceso al local y conservar registros necesarios para investigar disputas.</p></section>
  <section><h2>5. Planes, precios y beta</h2><p>Antes de confirmar mostramos el plan, ciclo, precio de referencia, importe efectivamente cobrado y condiciones de renovación. Durante una beta podemos activar planes por USD 0 aunque se muestre un precio comercial de referencia. No habrá cobro ni renovación automática mientras el checkout indique expresamente USD 0.</p><p>Cuando habilitemos pagos reales, el precio, impuestos aplicables, vigencia y renovación se mostrarán antes de contratar. Los beneficios dependen de la versión del plan y de los límites publicados.</p></section>
  <section><h2>6. Moderación y terminación</h2><p>Podemos retirar contenido o limitar cuentas que infrinjan la ley, derechos de terceros, estas reglas o nuestras <Link href="/normas-comunidad">normas de comunidad</Link>. Puedes dejar de usar el servicio en cualquier momento; ciertas obligaciones y registros necesarios sobreviven al cierre.</p></section>
  <section><h2>7. Responsabilidad</h2><p>Prestamos el servicio con diligencia razonable, pero no garantizamos disponibilidad ininterrumpida ni resultados comerciales específicos. Nada en estos términos excluye responsabilidad o derechos que no puedan excluirse legalmente.</p></section>
  <section><h2>8. Cambios, ley y contacto</h2><p>Podemos actualizar estas condiciones por razones legales, operativas o de producto y comunicaremos cambios materiales. Se interpretan conforme a las leyes de Ecuador. Para consultas o reclamos utiliza nuestra <Link href="/contact">página de contacto</Link>.</p></section>
</LegalPage> }
