import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage } from '@/components/legal/legal-page'
export const metadata: Metadata = { title: 'Política de privacidad — Vive Loja', description: 'Cómo Vive Loja recopila, utiliza, comparte y protege datos personales.', alternates: { canonical: 'https://viveloja.com/privacy' } }
export default function PrivacyPage() { return <LegalPage eyebrow="Tus datos" title="Política de privacidad" summary="Te explicamos con claridad qué datos tratamos, para qué los usamos y cómo puedes ejercer tus derechos en Ecuador.">
  <section><h2>1. Responsable y contacto</h2><p>Vive Loja es responsable del tratamiento realizado para operar esta plataforma. Puedes plantear consultas, solicitudes de derechos o reclamos mediante nuestra <Link href="/contact">página de contacto</Link>.</p></section>
  <section><h2>2. Datos que tratamos</h2><ul><li>Cuenta: nombre, correo, contraseña cifrada y preferencias.</li><li>Actividad: publicaciones, reseñas, mensajes, favoritos, reservas, reclamos y decisiones de moderación.</li><li>Negocios: información de contacto profesional, locales, equipo, planes, órdenes y evidencia de representación.</li><li>Técnicos: dirección IP o identificadores derivados, dispositivo, sesiones, registros de seguridad y uso.</li><li>Ubicación: solo cuando autorizas funciones cercanas o proporcionas coordenadas.</li></ul></section>
  <section><h2>3. Finalidades y bases</h2><p>Tratamos datos para ejecutar el servicio solicitado, autenticarte, publicar contenido, procesar reclamos y órdenes, prestar soporte, prevenir fraude, mantener seguridad, cumplir obligaciones y mejorar el producto. Cuando corresponda utilizamos consentimiento, ejecución contractual, obligación legal o interés legítimo sujeto a tus derechos.</p></section>
  <section><h2>4. Fuentes públicas y terceros</h2><p>Parte del directorio puede provenir de fuentes accesibles al público o proveedores de mapas y lugares. Indicamos atribución cuando aplica y permitimos solicitar correcciones. También usamos proveedores de alojamiento, correo, almacenamiento, mapas, analítica técnica y seguridad que procesan datos para prestarnos sus servicios.</p></section>
  <section><h2>5. Conservación</h2><p>Conservamos los datos mientras tu cuenta esté activa y después durante el tiempo razonablemente necesario para obligaciones legales, resolución de disputas, seguridad y respaldo. Evidencia de reclamos y registros de facturación pueden conservarse por períodos superiores cuando sean necesarios para acreditar decisiones o transacciones.</p></section>
  <section><h2>6. Seguridad y transferencias</h2><p>Aplicamos controles técnicos y organizativos razonables, como cifrado de contraseñas, permisos y registros. Ningún sistema es infalible. Algunos proveedores pueden procesar datos fuera de Ecuador; utilizamos mecanismos y garantías compatibles con la normativa aplicable.</p></section>
  <section><h2>7. Tus derechos</h2><p>Puedes solicitar información, acceso, rectificación, actualización, eliminación, oposición, limitación, portabilidad cuando corresponda y revisión de decisiones automatizadas. También puedes retirar un consentimiento sin afectar tratamientos anteriores. Verificaremos tu identidad antes de responder.</p></section>
  <section><h2>8. Menores y cambios</h2><p>La contratación de planes y administración de negocios está dirigida a personas con capacidad legal para contratar. Podemos actualizar esta política y comunicaremos cambios materiales mediante la plataforma u otros canales disponibles.</p></section>
</LegalPage> }
